const SENDINBLUE_TEMPLATES = {
  SOURCING_APPLICANT_CREATED: 102,
  FORGOT_PASSWORD: 99,
  INVITE_CLIENT: 84,
  BUDGET_SIGNATURE_REQUEST: 88,
  BUDGET_SIGNATURE_CONFIRMATION: 89,
  AVAILABILITY_UPDATE: 92,
  REPORT_BACKLOG: 93,
  INVOICE_REMINDER: 95,
  TICKET_ASSIGNMENT_NOTIFICATION: 96,
};

module.exports = { SENDINBLUE_TEMPLATES };
